export class PreApprovedDto {
    idPreAprobado: string;
    codigoCliente: string;
    numeroDocumento: string;
    tipoDocumento: string;
    cuenta: string;
    promedioAcreditacion: string;
    porcentajeEndeudamiento: string;
    montoPrestamo: string;
    edad: string;
    campanha: string;
    antiguedad: string;
    calificacionConti: string;
    calificacionBCP: string;
    referenciaAtraso: string;
    codeudor: string;
    mora: string;
    sucursal: string;
    ald: string;
    ros: string;
    cantidadPrestamo: string;
    pagoSalario: string;
    montoCuota: string;
    montoCapital: string;
    periodo: string;
    equifax: string;
    estadoBCP: string;
    estadoEquifax: string;
}